include: all_lint_rules.yaml

analyzer:
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    included_file_warning: ignore
    invalid_use_of_visible_for_testing_member: error
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'
    - '**/*.gen.dart'
    - '**/*.gr.dart'
    - '**/*.mocks.dart'
  plugins:
    - custom_lint

formatter:
  page_width: 100

linter:
  rules:
    do_not_use_environment: false
    prefer_final_parameters: false
    discarded_futures: false
    combinators_ordering: false
    eol_at_end_of_file: false
    no_leading_underscores_for_local_identifiers: false
    one_member_abstracts: false
    diagnostic_describe_all_properties: false
    prefer_double_quotes: false
    always_specify_types: false
    unnecessary_final: false
    prefer_expression_function_bodies: false
    always_put_required_named_parameters_first: false
    flutter_style_todos: false
    avoid_annotating_with_dynamic: false
    always_use_package_imports: false
    no_default_cases: false
    use_setters_to_change_properties: false
    document_ignores: false
    specify_nonobvious_local_variable_types: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false